# constants.py
"""
Constants for the Auxo trading bot.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
WEB_DIR = BASE_DIR / "web"
ENV_FILE = BASE_DIR / ".env"
AUDIT_LOG_FILE = BASE_DIR / "bot_audit.jsonl"
STATE_FILE = BASE_DIR / "bot_state.json"
DB_FILE = BASE_DIR / "trades.db"

DEFAULT_SETTINGS = {
    "asset_class": "crypto",
    "exchange": "coinbase",
    "symbol": "BTC",
    "watchlist": "BTC,ETH,SOL,XRP,DOGE,LINK,AVAX",
    "quote_currency": "GBP",
    "chart_mode": "line",
    "strategy": "self_learning",
    "starting_cash": 38.0,
    "trade_fee": 0.004,
    "poll_seconds": 15,
    "live_granularity": 3600,
    "live_candle_count": 300,
    "short_window": 5,
    "long_window": 20,
    "base_nb_candles_buy": 14,
    "base_nb_candles_sell": 24,
    "low_offset": 0.975,
    "low_offset_2": 0.955,
    "high_offset": 0.991,
    "high_offset_2": 0.997,
    "ewo_high": 2.327,
    "ewo_high_2": -2.327,
    "ewo_low": -20.988,
    "rsi_buy": 69,
    "max_position_pct": 0.25,
    "position_sizing_mode": "balance_fraction",
    "risk_per_trade_pct": 1.0,
    "min_order_value": 1.0,
    "stop_loss_pct": 2.0,
    "take_profit_pct": 3.0,
    "daily_loss_limit_pct": 5.0,
    "cooldown_seconds": 120,
    "sr_lookback_candles": 50,
    "use_sr_filter": False,
    "near_support_pct": 2.0,
    "min_resistance_distance_pct": 1.0,
    "min_sr_range_pct": 8.0,
    "min_reward_risk": 2.0,
    "support_stop_buffer_pct": 2.0,
    "use_dynamic_sr_exits": False,
    "resistance_target_buffer_pct": 0.5,
    "partial_take_profit_enabled": False,
    "partial_take_profit_pct": 50.0,
    "partial_take_profit_at_target_pct": 50.0,
    "trailing_stop_enabled": False,
    "trailing_stop_pct": 2.0,
    "trailing_activation_pct": 3.0,
    "live_trading_enabled": False,
    "live_order_type": "market",
    "live_limit_offset_pct": 0.05,
    "native_stop_enabled": False,
    "max_live_order_gbp": 5.0,
    "max_daily_live_loss_gbp": 2.0,
    "max_live_spread_pct": 0.35,
    "min_live_quote_volume": 1000.0,
    "backtest_slippage_pct": 0.10,
    "sr_zone_tolerance_pct": 0.6,
    "sr_min_touches": 2,
    "auto_disable_weak_pairs": True,
    "weak_pair_min_trades": 6,
    "weak_pair_expectancy_limit_pct": -0.3,
    "weak_pair_win_rate_limit_pct": 35.0,
    "regime_filter_enabled": False,
    "allow_trending_regime": True,
    "allow_ranging_regime": True,
    "allow_volatile_regime": False,
    "allow_dead_regime": False,
    "order_expiry_seconds": 180,
    "order_retry_limit": 1,
    "order_replace_enabled": True,
    "websocket_enabled": False,
    "closed_candle_only": True,
    "oanda_demo_trading_enabled": False,
    "max_oanda_open_trades": 3,
    "max_coinbase_open_trades": 3,
    "news_guard_enabled": False,
    "news_guard_before_minutes": 30,
    "news_guard_after_minutes": 30,
    "news_guard_block_high": True,
    "news_guard_block_medium": False,
    "news_guard_block_low": False,
    "opening_range_minutes": 15,
    "opening_range_atr_period": 14,
    "opening_range_manipulation_threshold": 0.20,
    "opening_range_stop_loss_atr_multiplier": 1.5,
    "opening_range_take_profit_atr_multiplier": 2.5,
    "oanda_account_type": "standard",
    "max_drawdown_pct": 20.0,
    "allow_short_selling": False,
    "telegram_enabled": False,
    "telegram_bot_token": "",
    "telegram_chat_id": "",
    "telegram_alert_on_buy": True,
    "telegram_alert_on_sell": True,
    "telegram_alert_on_error": True,
    "telegram_alert_on_daily_summary": True,
    "telegram_alert_on_drawdown": True,
    "telegram_drawdown_alert_pct": 10.0,
    "ema_short": 50,
    "ema_long": 200,
    "self_learning_enabled": True,
    "signal_confidence_threshold": 0.3,
    "min_signals_required": 1,
    "learning_history_size": 100,
    # Strategy Creator
    "strategy_creator_enabled": False,
    "strategy_evolution_enabled": False,
    "strategy_generations": 50,
    "strategy_population_size": 50,
    "strategy_confidence_threshold": 0.5,
    "strategy_auto_select": False,
    "strategy_evolution_frequency": 24,
    "strategy_max_active": 5,
    # Risk
    "risk_sizing_mode": "fixed",
    "kelly_fraction": 0.25,
    "atr_period": 14,
    "atr_multiplier": 2.0,
    "max_hold_hours": 24,
    "exit_strategies_enabled": {
        "rsi": True,
        "macd": True,
        "ma": True,
        "breakout": True,
        "time": True,
    },
    "rsi_oversold": 30,
    "rsi_overbought": 70,
    "ma_exit_period": 20,
    "active_exchange": "coinbase",
    "regime_adaptation_enabled": True,
    "strategy_switching_enabled": True,
    "min_regime_confidence": 0.5,
}